# ============================================================
#  main2.py  —  Blind Assistant for Raspberry Pi 4
#
#  Features:
#    - YOLO26n Object Detection  (fast, NMS-free)
#    - Indian Currency Recognition (custom fine-tuned model)
#    - Face Recognition (from single image, using face_recognition lib)
#    - Ultrasonic Sensor (HC-SR04) for distance warning
#    - IR Sensor for close obstacle detection
#    - Asynchronous TTS (pyttsx3) — never blocks vision loop
#    - Multi-threaded architecture for maximum speed
#
#  Requirements (install on Raspberry Pi):
#    pip install ultralytics opencv-python pyttsx3 gpiozero face-recognition
#    sudo apt-get install -y espeak cmake libboost-python-dev libopenblas-dev
#
#  Files needed:
#    yolo26n.pt             ← General objects (auto-downloaded by Ultralytics)
#    currency_yolo26n.pt    ← Your trained currency model (from Colab)
#    face_encodings.pkl     ← Generated by face_register.py
#
# ============================================================

import cv2
import os
import time
import queue
import pickle
import threading
import numpy as np

import pyttsx3
from ultralytics import YOLO

# face_recognition requires dlib, compile on RPi with:
# sudo apt-get install -y cmake libboost-python-dev
# pip install face-recognition
try:
    import face_recognition
    FACE_RECOGNITION_AVAILABLE = True
except ImportError:
    FACE_RECOGNITION_AVAILABLE = False
    print("WARNING: face_recognition not installed. Using Haar Cascade detection only.")

# gpiozero works only on Raspberry Pi hardware
try:
    from gpiozero import DistanceSensor, InputDevice
    GPIO_AVAILABLE = True
except Exception:
    GPIO_AVAILABLE = False
    print("WARNING: GPIO not available (running on non-Pi hardware or simulation mode).")


# ──────────────────────────────────────────────────────────────────
#  AUTO FACE REGISTRATION
#  Runs at every startup. If new photos added to known_faces/, it
#  automatically re-encodes and updates face_encodings.pkl.
# ──────────────────────────────────────────────────────────────────

KNOWN_FACES_DIR = "known_faces"
ENCODINGS_FILE  = "face_encodings.pkl"


def _get_latest_photo_mtime(folder):
    """Return the most recent mtime of any image file inside known_faces/."""
    latest = 0.0
    exts   = {'.jpg', '.jpeg', '.png', '.bmp'}
    for root, _, files in os.walk(folder):
        for f in files:
            if os.path.splitext(f)[1].lower() in exts:
                t = os.path.getmtime(os.path.join(root, f))
                if t > latest:
                    latest = t
    return latest


def auto_register_faces():
    """
    Called automatically every time main2.py starts.
    Compares modification times:
      - If any photo in known_faces/ is NEWER than face_encodings.pkl
        → re-encode all faces and overwrite the .pkl.
      - If .pkl is already up to date → skip (fast startup).
    Just drop new photos into known_faces/PersonName/ and restart.
    """
    print("[FaceReg] Checking for new faces...")

    if not FACE_RECOGNITION_AVAILABLE:
        print("[FaceReg] face_recognition not installed — skipping.")
        return

    if not os.path.isdir(KNOWN_FACES_DIR):
        os.makedirs(KNOWN_FACES_DIR)
        print(f"[FaceReg] Created '{KNOWN_FACES_DIR}/' — add sub-folders with photos.")
        print(f"           Example: known_faces/Rajendran/photo1.jpg")
        return

    # Compare timestamps
    photo_mtime = _get_latest_photo_mtime(KNOWN_FACES_DIR)
    if photo_mtime == 0.0:
        print("[FaceReg] No photos found in known_faces/. Skipping.")
        return

    pkl_mtime = os.path.getmtime(ENCODINGS_FILE) if os.path.exists(ENCODINGS_FILE) else 0.0
    if pkl_mtime >= photo_mtime:
        print("[FaceReg] Encodings are up to date — skipping re-registration.")
        return

    # ── Re-encode all faces ─────────────────────────────────
    print("[FaceReg] New photos detected — building face encodings...")
    known_encodings = []
    known_names     = []
    exts            = {'.jpg', '.jpeg', '.png', '.bmp'}

    persons = sorted([
        d for d in os.listdir(KNOWN_FACES_DIR)
        if os.path.isdir(os.path.join(KNOWN_FACES_DIR, d))
    ])

    for person in persons:
        person_dir = os.path.join(KNOWN_FACES_DIR, person)
        photos     = [f for f in os.listdir(person_dir)
                      if os.path.splitext(f)[1].lower() in exts]
        added = 0
        for photo in photos:
            try:
                img  = face_recognition.load_image_file(os.path.join(person_dir, photo))
                encs = face_recognition.face_encodings(img)
                if not encs:
                    print(f"[FaceReg]   ⚠ No face in '{photo}'. Skipping.")
                    continue
                known_encodings.append(encs[0])
                known_names.append(person)
                added += 1
            except Exception as e:
                print(f"[FaceReg]   ⚠ Error '{photo}': {e}")
        print(f"[FaceReg]   ✓ {person}: {added} photo(s) encoded.")

    if known_encodings:
        with open(ENCODINGS_FILE, 'wb') as f:
            pickle.dump({"encodings": known_encodings, "names": known_names}, f)
        print(f"[FaceReg] ✅ {len(known_encodings)} encoding(s) saved → '{ENCODINGS_FILE}'")
    else:
        print("[FaceReg] ⚠ No valid faces found. Check photo quality.")

# ──────────────────────────────────────────────────────────────────
#  CONFIGURATION — Adjust these values as needed
# ──────────────────────────────────────────────────────────────────
CONFIG = {
    # Camera
    "CAMERA_INDEX":     0,
    "FRAME_WIDTH":      640,
    "FRAME_HEIGHT":     480,

    # YOLO — General model (auto-downloaded)
    "YOLO_GENERAL_MODEL":  "yolo26n.pt",

    # Currency model — supports both formats from Colab export:
    #   Option A (easier):  rename best.pt  → "currency_yolo26n.pt"
    #   Option B (faster):  rename best_ncnn_model folder → "currency_yolo26n_ncnn_model"
    # The script will auto-detect whichever exists.
    "YOLO_CURRENCY_MODEL_PT":   "currency_yolo26n.pt",
    "YOLO_CURRENCY_MODEL_NCNN": "currency_yolo26n_ncnn_model",

    "YOLO_CONF":  0.45,
    "YOLO_IMGSZ": 640,

    # Face recognition
    "FACE_ENCODINGS_FILE": "face_encodings.pkl",
    "FACE_TOLERANCE":      0.50,   # Lower = stricter match

    # Sensors — GPIO pins (BCM numbering)
    "ULTRASONIC_TRIGGER_PIN": 4,
    "ULTRASONIC_ECHO_PIN":    17,
    "IR_SENSOR_PIN":          24,  # Change if your IR pin is different
    "OBSTACLE_WARN_CM":       60,  # Warn if obstacle closer than 60 cm

    # TTS
    "SPEECH_RATE":     145,
    "TTS_COOLDOWN_S":  2.5,  # seconds between same message

    # Frame skipping — run expensive models every N frames to save CPU
    "CURRENCY_CHECK_EVERY": 3,   # Currency model: every 3 frames
    "FACE_CHECK_EVERY":     8,   # Face recognition: every 8 frames
}


# ──────────────────────────────────────────────────────────────────
#  SECTION 1 — Async TTS Engine
# ──────────────────────────────────────────────────────────────────

class TTSSpeaker:
    """
    Runs pyttsx3 in its own thread with a queue.
    This ensures the vision loop is NEVER blocked by speaking.
    Deduplicates messages within the cooldown window.
    """

    def __init__(self, rate: int = 145, cooldown: float = 2.5):
        self._queue     = queue.Queue(maxsize=5)
        self._last_msg  = {}
        self._cooldown  = cooldown
        self._rate      = rate
        t = threading.Thread(target=self._run, daemon=True)
        t.start()

    def say(self, text: str):
        now = time.time()
        if now - self._last_msg.get(text, 0) < self._cooldown:
            return  # Skip duplicate within cooldown window
        self._last_msg[text] = now
        try:
            self._queue.put_nowait(text)
        except queue.Full:
            pass  # Drop if queue is full — keeps real-time

    def _run(self):
        # pyttsx3 MUST be initialized in the thread where it speaks on Windows!
        # Otherwise SAPI5 fails silently.
        import pyttsx3
        engine = pyttsx3.init()
        engine.setProperty('rate', self._rate)
        
        while True:
            text = self._queue.get()
            try:
                engine.say(text)
                engine.runAndWait()
            except Exception as e:
                print(f"TTS Error: {e}")


# ──────────────────────────────────────────────────────────────────
#  SECTION 2 — Camera Thread (keeps buffer fresh)
# ──────────────────────────────────────────────────────────────────

class CameraStream:
    """
    Runs capture in a background thread to prevent frame lag.
    Always provides the latest frame.
    """

    def __init__(self, index: int, width: int, height: int):
        import platform
        # Use V4L2 on Linux (Raspberry Pi), default backend on Windows/Mac
        if platform.system() == "Linux":
            self._cap = cv2.VideoCapture(index, cv2.CAP_V4L2)
        else:
            self._cap = cv2.VideoCapture(index)  # Windows/Mac default
        self._cap.set(cv2.CAP_PROP_FRAME_WIDTH,  width)
        self._cap.set(cv2.CAP_PROP_FRAME_HEIGHT, height)
        self._cap.set(cv2.CAP_PROP_BUFFERSIZE, 1)  # Minimize buffer lag
        self._frame = None
        self._lock  = threading.Lock()
        self._running = True
        threading.Thread(target=self._capture_loop, daemon=True).start()
        print(f"Camera {index} started at {width}×{height}")

    def _capture_loop(self):
        while self._running:
            ret, frame = self._cap.read()
            if ret:
                with self._lock:
                    self._frame = frame

    def read(self):
        with self._lock:
            return self._frame.copy() if self._frame is not None else None

    def stop(self):
        self._running = False
        self._cap.release()


# ──────────────────────────────────────────────────────────────────
#  SECTION 3 — Sensor Monitor Thread
# ──────────────────────────────────────────────────────────────────

class SensorMonitor:
    """
    Monitors Ultrasonic (HC-SR04) and IR sensor in a background thread.
    Fires a callback when an obstacle is detected.
    """

    def __init__(self, tts: TTSSpeaker, cfg: dict):
        self.tts     = tts
        self.cfg     = cfg
        self.dist_cm = 999.0
        self.ir_triggered = False
        self._running = True

        if GPIO_AVAILABLE:
            try:
                self._ultrasonic = DistanceSensor(
                    echo    = cfg["ULTRASONIC_ECHO_PIN"],
                    trigger = cfg["ULTRASONIC_TRIGGER_PIN"],
                    max_distance = 4.0
                )
                self._ir = InputDevice(cfg["IR_SENSOR_PIN"])
            except Exception as e:
                print(f"Sensor init error: {e}")
                self._ultrasonic = None
                self._ir = None
        else:
            self._ultrasonic = None
            self._ir = None

        threading.Thread(target=self._monitor_loop, daemon=True).start()

    def _monitor_loop(self):
        while self._running:
            if self._ultrasonic:
                try:
                    self.dist_cm = self._ultrasonic.distance * 100.0
                except Exception:
                    self.dist_cm = 999.0

            if self._ir:
                try:
                    self.ir_triggered = self._ir.is_active
                    if self.ir_triggered:
                        self.tts.say("Object very close. Stop.")
                except Exception:
                    self.ir_triggered = False

            time.sleep(0.2)  # Poll at 5 Hz

    def stop(self):
        self._running = False


# ──────────────────────────────────────────────────────────────────
#  SECTION 4 — Face Recognition Engine
# ──────────────────────────────────────────────────────────────────

class FaceEngine:
    """
    Loads pre-computed face encodings and recognizes faces in a frame.
    Falls back to Haar Cascade detect-only if face_recognition not available.
    """

    def __init__(self, encodings_file: str, tolerance: float = 0.50):
        self.tolerance = tolerance
        self.known_enc  = []
        self.known_names = []
        self._haar = cv2.CascadeClassifier(
            cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
        )

        if FACE_RECOGNITION_AVAILABLE and os.path.exists(encodings_file):
            with open(encodings_file, 'rb') as f:
                data = pickle.load(f)
            self.known_enc   = data["encodings"]
            self.known_names = data["names"]
            print(f"Loaded {len(self.known_enc)} face encoding(s) from '{encodings_file}'.")
        elif not os.path.exists(encodings_file):
            print(f"'{encodings_file}' not found. Running face detection only (no recognition).")
        else:
            print("face_recognition unavailable. Running Haar detection only.")

    def process(self, frame: np.ndarray):
        """
        Returns a list of (name, x, y, w, h) tuples for each face.
        name = person name if recognized, "Unknown" if detected but not matched.
        """
        results = []

        if FACE_RECOGNITION_AVAILABLE and self.known_enc:
            # Use face_recognition for identity matching
            # Resize to 1/2 for speed, then scale back
            small = cv2.resize(frame, (0, 0), fx=0.5, fy=0.5)
            rgb   = cv2.cvtColor(small, cv2.COLOR_BGR2RGB)
            locs  = face_recognition.face_locations(rgb, model="hog")
            encs  = face_recognition.face_encodings(rgb, locs)

            for enc, (top, right, bottom, left) in zip(encs, locs):
                name = "Unknown"
                if self.known_enc:
                    matches  = face_recognition.compare_faces(self.known_enc, enc, self.tolerance)
                    distances= face_recognition.face_distance(self.known_enc, enc)
                    best_idx = np.argmin(distances)
                    if matches[best_idx]:
                        name = self.known_names[best_idx]

                # Scale coordinates back to original size
                top    *= 2; right *= 2; bottom *= 2; left *= 2
                x, y, w, h = left, top, right - left, bottom - top
                results.append((name, x, y, w, h))

        else:
            # Haar Cascade only (detection, no recognition)
            gray  = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            faces = self._haar.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=4)
            for (x, y, w, h) in faces:
                results.append(("Person", x, y, w, h))

        return results


# ──────────────────────────────────────────────────────────────────
#  SECTION 5 — Main Vision Loop
# ──────────────────────────────────────────────────────────────────

import os  # needed for os.path.exists above

CURRENCY_LABELS = {
    "10_rupee":   "10 Rupees",
    "20_rupee":   "20 Rupees",
    "50_rupee":   "50 Rupees",
    "100_rupee":  "100 Rupees",
    "200_rupee":  "200 Rupees",
    "500_rupee":  "500 Rupees",
    "2000_rupee": "2000 Rupees",
}

# Labels from the general YOLO model that are useful for the blind
RELEVANT_OBJECTS = {
    "person", "car", "truck", "bus", "bicycle", "motorcycle",
    "chair", "door", "stairs", "bottle", "cup", "cell phone",
    "laptop", "tv", "book", "bag", "umbrella", "cat", "dog",
}


def draw_label(frame, text, x1, y1, color=(0, 255, 0)):
    cv2.rectangle(frame, (x1 - 1, y1 - 22), (x1 + len(text) * 9, y1), color, -1)
    cv2.putText(frame, text, (x1, y1 - 5),
                cv2.FONT_HERSHEY_SIMPLEX, 0.55, (0, 0, 0), 1, cv2.LINE_AA)


def main():
    print("\n" + "=" * 55)
    print("  BLIND ASSISTANT STARTING")
    print("=" * 55 + "\n")

    tts = TTSSpeaker(rate=CONFIG["SPEECH_RATE"], cooldown=CONFIG["TTS_COOLDOWN_S"])
    tts.say("Blind Assistant starting. Please wait.")

    # ── Models ──────────────────────────────────────────────────
    print("Loading YOLO26n general model...")
    general_model = YOLO(CONFIG["YOLO_GENERAL_MODEL"])

    # Auto-detect currency model: prefer NCNN (faster on Pi), fall back to .pt
    currency_model = None
    ncnn_path = CONFIG["YOLO_CURRENCY_MODEL_NCNN"]
    pt_path   = CONFIG["YOLO_CURRENCY_MODEL_PT"]

    if os.path.isdir(ncnn_path):
        print(f"Loading currency model (NCNN — fastest on Pi): {ncnn_path}")
        currency_model = YOLO(ncnn_path)
    elif os.path.exists(pt_path):
        print(f"Loading currency model (PyTorch): {pt_path}")
        currency_model = YOLO(pt_path)
    else:
        print("⚠ Currency model not found. Copy 'currency_yolo26n.pt' or")
        print("  'currency_yolo26n_ncnn_model/' folder to this directory.")
        print("  Object detection and face recognition will still work.")

    # ── Step 0: Auto-register faces before loading engine ────────
    # Detects new photos in known_faces/ and rebuilds face_encodings.pkl.
    # This happens automatically every time main2.py starts.
    auto_register_faces()

    # ── Face Engine ─────────────────────────────────────────────
    face_engine = FaceEngine(
        encodings_file=ENCODINGS_FILE,
        tolerance=CONFIG["FACE_TOLERANCE"]
    )

    # ── Camera ──────────────────────────────────────────────────
    cam = CameraStream(
        index  = CONFIG["CAMERA_INDEX"],
        width  = CONFIG["FRAME_WIDTH"],
        height = CONFIG["FRAME_HEIGHT"]
    )
    time.sleep(1.5)  # Let camera warm up

    # ── Sensors ──────────────────────────────────────────────────
    # Safe on Windows: GPIO_AVAILABLE=False so no pins are touched,
    # dist_cm stays 999 and ir_triggered stays False.
    sensors = SensorMonitor(tts, CONFIG)

    tts.say("System ready.")
    print("System ready. Press Q to quit.\n")

    # ── Display window setup ───────────────────────────────────
    WIN_NAME   = "Blind Assistant - Detection View"
    DISP_SCALE = 2          # Scale camera 320×240 → 960×720
    PANEL_W    = 380        # Width of right-side info panel
    DISP_H     = CONFIG["FRAME_HEIGHT"] * DISP_SCALE   # 720
    DISP_W     = CONFIG["FRAME_WIDTH"]  * DISP_SCALE   # 960
    TOTAL_W    = DISP_W + PANEL_W                       # 1340

    cv2.namedWindow(WIN_NAME, cv2.WINDOW_NORMAL)
    cv2.resizeWindow(WIN_NAME, TOTAL_W, DISP_H)

    frame_count          = 0
    fps_timer            = time.time()
    display_fps          = 0
    FACE_CHECK_EVERY     = CONFIG["FACE_CHECK_EVERY"]
    CURRENCY_CHECK_EVERY = CONFIG["CURRENCY_CHECK_EVERY"]

    while True:
        frame = cam.read()
        if frame is None:
            time.sleep(0.01)
            continue

        frame_count += 1

        # ── FPS Calculation ───────────────────────────────────
        if frame_count % 30 == 0:
            elapsed     = time.time() - fps_timer
            display_fps = 30 / elapsed if elapsed > 0 else 0
            fps_timer   = time.time()

        # ── STEP 1: YOLO26n General Object Detection ──────────
        results = general_model(
            frame,
            conf    = CONFIG["YOLO_CONF"],
            imgsz   = CONFIG["YOLO_IMGSZ"],
            verbose = False,
        )

        detected_currency_region = None
        person_detected          = False
        object_spoken            = False

        for r in results:
            for box in r.boxes:
                cls_id  = int(box.cls[0])
                label   = general_model.names[cls_id]
                conf    = float(box.conf[0])
                x1, y1, x2, y2 = map(int, box.xyxy[0])

                # Draw bounding box
                cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 220, 0), 1)
                draw_label(frame, f"{label} {conf:.0%}", x1, y1, (0, 220, 0))

                # Trigger voice for relevant objects
                if label in RELEVANT_OBJECTS:
                    if label == "person":
                        person_detected = True
                        # Face recognition handled later
                    else:
                        ultrasonic = getattr(sensors, '_ultrasonic', None)
                        if GPIO_AVAILABLE and ultrasonic and sensors.dist_cm < 900:
                            dist_m = sensors.dist_cm / 100.0
                            tts.say(f"{label} in {dist_m:.1f} meter")
                        else:
                            tts.say(f"{label} ahead")
                        object_spoken = True

                # Flag currency region for the currency model
                if label in ("book", "paper") and currency_model:
                    detected_currency_region = (x1, y1, x2, y2)

        # Fallback: if no specific object matched but obstacle is very close (<5m)
        ultrasonic = getattr(sensors, '_ultrasonic', None)
        if not object_spoken and not person_detected:
            if GPIO_AVAILABLE and ultrasonic and sensors.dist_cm < 500:
                tts.say("There is an object in front of you.")

        # ── STEP 4: Build display canvas ───────────────────────

        # Scale up the camera frame for viewing (YOLO still ran on small frame)
        big_frame = cv2.resize(frame, (DISP_W, DISP_H), interpolation=cv2.INTER_LINEAR)

        # Create dark side panel
        panel = np.zeros((DISP_H, PANEL_W, 3), dtype=np.uint8)
        panel[:] = (28, 28, 28)  # dark background

        # ── Panel header ──────────────────────────────────────
        cv2.rectangle(panel, (0, 0), (PANEL_W, 50), (45, 45, 45), -1)
        cv2.putText(panel, "BLIND ASSISTANT", (12, 22),
                    cv2.FONT_HERSHEY_DUPLEX, 0.65, (100, 255, 100), 1, cv2.LINE_AA)
        cv2.putText(panel, f"FPS: {display_fps:.1f}    Q = Quit", (12, 44),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.50, (160, 160, 160), 1, cv2.LINE_AA)
        cv2.line(panel, (0, 50), (PANEL_W, 50), (70, 70, 70), 1)

        y = 70  # cursor y for panel text

        def panel_section(title, color=(120, 220, 255)):
            """Draw a section title bar."""
            nonlocal y
            cv2.rectangle(panel, (0, y), (PANEL_W, y + 26), (50, 50, 50), -1)
            cv2.putText(panel, f"  {title}", (8, y + 18),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.55, color, 1, cv2.LINE_AA)
            y += 30

        def panel_row(label, value, val_color=(255, 255, 255)):
            """Draw one data row: label on left, value on right."""
            nonlocal y
            cv2.putText(panel, label, (12, y + 15),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.50, (160, 160, 160), 1, cv2.LINE_AA)
            cv2.putText(panel, str(value), (160, y + 15),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.55, val_color, 1, cv2.LINE_AA)
            y += 26

        # ── SENSORS section ─────────────────────────────────
        panel_section("SENSORS", (120, 220, 255))
        if GPIO_AVAILABLE and sensors._ultrasonic:
            dist_val   = f"{sensors.dist_cm:.0f} cm"
            dist_color = (0, 80, 255) if sensors.dist_cm < CONFIG["OBSTACLE_WARN_CM"] else (80, 255, 80)
            panel_row("Ultrasonic", dist_val, dist_color)
            ir_val   = "TRIGGERED" if sensors.ir_triggered else "Clear"
            ir_color = (0, 80, 255) if sensors.ir_triggered else (80, 255, 80)
            panel_row("IR Sensor", ir_val, ir_color)
        else:
            panel_row("Status", "Offline (PC mode)", (120, 120, 120))
        y += 6

        # ── OBJECTS section ─────────────────────────────────
        panel_section("DETECTED OBJECTS", (100, 255, 160))
        obj_found = False
        for r in results:
            for box in r.boxes:
                lbl  = general_model.names[int(box.cls[0])]
                conf = float(box.conf[0])
                panel_row(lbl.capitalize(), f"{conf:.0%}", (255, 255, 255))
                obj_found = True
        if not obj_found:
            panel_row("None", "", (80, 80, 80))
        y += 6

        # ── CURRENCY section ───────────────────────────────
        panel_section("CURRENCY", (0, 200, 255))
        if currency_model:
            curr_results = currency_model(
                frame, conf=0.60, imgsz=CONFIG["YOLO_IMGSZ"], verbose=False
            ) if frame_count % CURRENCY_CHECK_EVERY == 0 else []
            curr_found = False
            for r in curr_results:
                for box in r.boxes:
                    raw_lbl = currency_model.names[int(box.cls[0])]
                    spoken  = CURRENCY_LABELS.get(raw_lbl, raw_lbl)
                    conf    = float(box.conf[0])
                    panel_row("Note", f"Rs {spoken}  {conf:.0%}", (0, 220, 255))
                    # Draw on big frame too
                    x1s = int(box.xyxy[0][0]) * DISP_SCALE
                    y1s = int(box.xyxy[0][1]) * DISP_SCALE
                    x2s = int(box.xyxy[0][2]) * DISP_SCALE
                    y2s = int(box.xyxy[0][3]) * DISP_SCALE
                    cv2.rectangle(big_frame, (x1s, y1s), (x2s, y2s), (0, 215, 255), 2)
                    cv2.putText(big_frame, f"Rs {spoken}", (x1s, y1s - 8),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.75, (0, 215, 255), 2)
                    tts.say(f"{spoken}.")
                    curr_found = True
            if not curr_found:
                panel_row("None", "", (80, 80, 80))
        else:
            panel_row("Model", "Not loaded", (80, 80, 80))
        y += 6

        # ── FACES section ──────────────────────────────────
        panel_section("FACES", (255, 120, 60))
        if frame_count % FACE_CHECK_EVERY == 0 and person_detected:
            faces = face_engine.process(frame)
            face_found = False
            for (name, x, y_f, w_f, h_f) in faces:
                color = (255, 80, 0) if name != "Unknown" else (80, 80, 255)
                # Scale box to big frame
                cv2.rectangle(big_frame,
                              (x * DISP_SCALE, y_f * DISP_SCALE),
                              ((x + w_f) * DISP_SCALE, (y_f + h_f) * DISP_SCALE), color, 2)
                cv2.putText(big_frame, name,
                            (x * DISP_SCALE, y_f * DISP_SCALE - 10),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.80, color, 2)
                face_color = (80, 80, 255) if name == "Unknown" else (255, 180, 80)
                panel_row("Person", name, face_color)
                if name == "Unknown":
                    tts.say("It is an unknown person.")
                else:
                    tts.say(f"It is {name}.")
                face_found = True
            if not face_found:
                panel_row("None", "", (80, 80, 80))
        else:
            panel_row("", "Scanning...", (80, 80, 80))
        y += 6

        # ── Legend at panel bottom ───────────────────────────
        legend_y = DISP_H - 70
        cv2.line(panel, (0, legend_y), (PANEL_W, legend_y), (60, 60, 60), 1)
        for i, (text, col) in enumerate([
            ("Green boxes = Objects",   (80, 255, 80)),
            ("Yellow boxes = Currency", (0, 215, 255)),
            ("Blue/Orange = Face",      (255, 160, 80)),
        ]):
            cv2.putText(panel, text, (12, legend_y + 18 + i * 20),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.42, col, 1, cv2.LINE_AA)

        # ── Scale up bounding boxes on big_frame ───────────────
        for r in results:
            for box in r.boxes:
                x1, y1, x2, y2 = map(int, box.xyxy[0])
                lbl  = general_model.names[int(box.cls[0])]
                conf = float(box.conf[0])
                cv2.rectangle(big_frame,
                              (x1 * DISP_SCALE, y1 * DISP_SCALE),
                              (x2 * DISP_SCALE, y2 * DISP_SCALE), (0, 220, 0), 2)
                cv2.putText(big_frame, f"{lbl} {conf:.0%}",
                            (x1 * DISP_SCALE, max(y1 * DISP_SCALE - 8, 20)),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.68, (0, 255, 0), 2, cv2.LINE_AA)

        # ── Stitch frame + panel side by side ─────────────────
        canvas = np.hstack([big_frame, panel])

        # ── STEP 5: Show window ───────────────────────────────
        cv2.imshow(WIN_NAME, canvas)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break


    # ── Cleanup ───────────────────────────────────────────────
    cam.stop()
    sensors.stop()
    cv2.destroyAllWindows()
    print("Assistant stopped.")



if __name__ == "__main__":
    main()